import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:uuid/uuid.dart';

import 'tables.dart';

export 'tables.dart';

// This file is generated by build_runner. Red errors on this line are normal
// until you run: dart run build_runner build --delete-conflicting-outputs
part 'database.g.dart';

@DriftDatabase(
  tables: [
    Categories,
    IncomeSources,
    Transactions,
    TransactionItems,
    BudgetStrategies,
    BudgetBuckets,
    Debts,
    SavingsGoals,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? executor])
      : super(executor ?? _openConnection());

  @override
  // Bump this every time a table changes, and add a step in onUpgrade.
  int get schemaVersion => 6;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          await m.createAll();
          await _seedDefaults();
        },
        onUpgrade: (m, from, to) async {
          // Runs on phones that already have an older database, so nobody
          // loses their data when the app updates.
          if (from < 2) {
            await m.addColumn(debts, debts.paidBeforeTrackingMinor);
          }
          if (from < 3) {
            await m.createTable(transactionItems);
            await (update(categories)..where((c) => c.name.equals('Utilities')))
                .write(const CategoriesCompanion(name: Value('Bills & Utilities')));
            await into(categories).insert(
              CategoriesCompanion.insert(
                name: 'Home Supplies',
                kind: CategoryKind.expense,
                iconKey: 'cleaning_services',
                budgetTag: const Value(BudgetTag.essentials),
                sortOrder: const Value(1),
              ),
            );
          }
          if (from < 4) {
            await m.addColumn(savingsGoals, savingsGoals.startingAmountMinor);
          }
          if (from < 5) {
            await m.addColumn(categories, categories.parentId);
            await m.addColumn(transactions, transactions.payPeriod);
            final bills = await (select(categories)
                  ..where((c) => c.name.equals('Bills & Utilities'))
                  ..limit(1))
                .getSingleOrNull();
            if (bills != null) await _seedBillSubcategories(bills.id);
          }
          if (from < 6) {
            await m.addColumn(transactions, transactions.paymentMethod);
          }
        },
        beforeOpen: (details) async {
          await customStatement('PRAGMA foreign_keys = ON');
        },
      );

  static QueryExecutor _openConnection() => driftDatabase(name: 'tidewise');

  // --------------------------------------------------------------------------
  // First-launch defaults: starter categories and preset budget strategies.
  // --------------------------------------------------------------------------
  Future<void> _seedDefaults() async {
    const uuid = Uuid();

    const expenseCategories = <(String, String, BudgetTag)>[
      ('Housing & Rent', 'home', BudgetTag.essentials),
      ('Groceries', 'shopping_cart', BudgetTag.essentials),
      ('Home Supplies', 'cleaning_services', BudgetTag.essentials),
      ('Transport', 'directions_bus', BudgetTag.essentials),
      ('Bills & Utilities', 'bolt', BudgetTag.essentials),
      ('Phone & Internet', 'phone_android', BudgetTag.essentials),
      ('Health', 'medical_services', BudgetTag.essentials),
      ('Education', 'school', BudgetTag.essentials),
      ('Family Support', 'family_restroom', BudgetTag.essentials),
      ('Dining Out', 'restaurant', BudgetTag.wants),
      ('Entertainment', 'movie', BudgetTag.wants),
      ('Shopping', 'shopping_bag', BudgetTag.wants),
      ('Personal Care', 'spa', BudgetTag.wants),
      ('Gifts & Giving', 'card_giftcard', BudgetTag.wants),
      ('Other', 'more_horiz', BudgetTag.wants),
    ];

    const incomeCategories = <(String, String)>[
      ('Salary', 'work'),
      ('Business', 'storefront'),
      ('Freelance & Gigs', 'handyman'),
      ('Gifts Received', 'redeem'),
      ('Other Income', 'more_horiz'),
    ];

    const presets = <_PresetSeed>[
      _PresetSeed(
        name: '50/30/20',
        description: 'Needs, wants, and savings. A simple, popular start.',
        isActive: true,
        buckets: [
          _BucketSeed('Needs', 5000, [BudgetTag.essentials]),
          _BucketSeed('Wants', 3000, [BudgetTag.wants]),
          _BucketSeed('Savings & Debt', 2000, [
            BudgetTag.longTermSavings,
            BudgetTag.shortTermSavings,
            BudgetTag.debt,
          ]),
        ],
      ),
      _PresetSeed(
        name: '50/15/5/30',
        description:
            'Essentials, long-term savings, short-term savings, and flexible spending.',
        buckets: [
          _BucketSeed('Essentials', 5000, [BudgetTag.essentials, BudgetTag.debt]),
          _BucketSeed('Long-term Savings', 1500, [BudgetTag.longTermSavings]),
          _BucketSeed('Short-term Savings', 500, [BudgetTag.shortTermSavings]),
          _BucketSeed('Flexible Spending', 3000, [BudgetTag.wants]),
        ],
      ),
      _PresetSeed(
        name: '70/20/10',
        description: 'Living costs, savings, and extra debt payments.',
        buckets: [
          _BucketSeed('Living Costs', 7000, [BudgetTag.essentials, BudgetTag.wants]),
          _BucketSeed('Savings', 2000, [
            BudgetTag.longTermSavings,
            BudgetTag.shortTermSavings,
          ]),
          _BucketSeed('Debt', 1000, [BudgetTag.debt]),
        ],
      ),
      _PresetSeed(
        name: 'Pay Yourself First',
        description: 'Save 20% the moment money arrives, then live on the rest.',
        buckets: [
          _BucketSeed('Savings First', 2000, [
            BudgetTag.longTermSavings,
            BudgetTag.shortTermSavings,
          ]),
          _BucketSeed('Everything Else', 8000, [
            BudgetTag.essentials,
            BudgetTag.wants,
            BudgetTag.debt,
          ]),
        ],
      ),
    ];

    await batch((b) {
      b.insertAll(categories, [
        for (var i = 0; i < expenseCategories.length; i++)
          CategoriesCompanion.insert(
            name: expenseCategories[i].$1,
            kind: CategoryKind.expense,
            iconKey: expenseCategories[i].$2,
            budgetTag: Value(expenseCategories[i].$3),
            sortOrder: Value(i),
          ),
        for (var i = 0; i < incomeCategories.length; i++)
          CategoriesCompanion.insert(
            name: incomeCategories[i].$1,
            kind: CategoryKind.income,
            iconKey: incomeCategories[i].$2,
            sortOrder: Value(i),
          ),
      ]);

      for (final preset in presets) {
        final strategyId = uuid.v4();
        b.insert(
          budgetStrategies,
          BudgetStrategiesCompanion.insert(
            id: Value(strategyId),
            name: preset.name,
            description: Value(preset.description),
            isPreset: const Value(true),
            isActive: Value(preset.isActive),
          ),
        );
        b.insertAll(budgetBuckets, [
          for (var i = 0; i < preset.buckets.length; i++)
            BudgetBucketsCompanion.insert(
              strategyId: strategyId,
              name: preset.buckets[i].name,
              basisPoints: preset.buckets[i].basisPoints,
              tags: preset.buckets[i].tags.map((t) => t.name).join(','),
              sortOrder: Value(i),
            ),
        ]);
      }
    });

    final bills = await (select(categories)
          ..where((c) => c.name.equals('Bills & Utilities'))
          ..limit(1))
        .getSingleOrNull();
    if (bills != null) await _seedBillSubcategories(bills.id);
  }

  Future<void> _seedBillSubcategories(String parentId) async {
    const subs = [
      ('Electricity', 'bolt'),
      ('Water', 'water_drop'),
      ('Internet & Wifi', 'wifi'),
      ('Cooking gas', 'local_fire_department'),
    ];
    for (var i = 0; i < subs.length; i++) {
      await into(categories).insert(
        CategoriesCompanion.insert(
          name: subs[i].$1,
          kind: CategoryKind.expense,
          iconKey: subs[i].$2,
          budgetTag: const Value(BudgetTag.essentials),
          parentId: Value(parentId),
          sortOrder: Value(i),
        ),
      );
    }
  }
}

/// Turns a bucket's stored "tag1,tag2" text back into a list of BudgetTags.
extension BudgetBucketTags on BudgetBucket {
  List<BudgetTag> get tagList => tags
      .split(',')
      .where((t) => t.isNotEmpty)
      .map(BudgetTag.values.byName)
      .toList();
}

class _PresetSeed {
  const _PresetSeed({
    required this.name,
    required this.description,
    required this.buckets,
    this.isActive = false,
  });

  final String name;
  final String description;
  final List<_BucketSeed> buckets;
  final bool isActive;
}

class _BucketSeed {
  const _BucketSeed(this.name, this.basisPoints, this.tags);

  final String name;
  final int basisPoints;
  final List<BudgetTag> tags;
}
