import 'package:flutter/material.dart';

/// Maps the iconKey stored in the database to an actual icon.
const Map<String, IconData> _icons = {
  'home': Icons.home_rounded,
  'shopping_cart': Icons.shopping_cart_rounded,
  'cleaning_services': Icons.cleaning_services_rounded,
  'directions_bus': Icons.directions_bus_rounded,
  'bolt': Icons.bolt_rounded,
  'phone_android': Icons.phone_android_rounded,
  'medical_services': Icons.medical_services_rounded,
  'school': Icons.school_rounded,
  'family_restroom': Icons.family_restroom_rounded,
  'restaurant': Icons.restaurant_rounded,
  'movie': Icons.movie_rounded,
  'shopping_bag': Icons.shopping_bag_rounded,
  'spa': Icons.spa_rounded,
  'card_giftcard': Icons.card_giftcard_rounded,
  'more_horiz': Icons.more_horiz_rounded,
  'work': Icons.work_rounded,
  'storefront': Icons.storefront_rounded,
  'handyman': Icons.handyman_rounded,
  'redeem': Icons.redeem_rounded,
  'savings': Icons.savings_rounded,
  'shield': Icons.shield_rounded,
  'directions_car': Icons.directions_car_rounded,
  'flight': Icons.flight_rounded,
  'phone_iphone': Icons.phone_iphone_rounded,
  'celebration': Icons.celebration_rounded,
  'beach_access': Icons.beach_access_rounded,
  'favorite': Icons.favorite_rounded,
  'trending_up': Icons.trending_up_rounded,
  'payments': Icons.payments_rounded,
  'water_drop': Icons.water_drop_rounded,
  'wifi': Icons.wifi_rounded,
  'local_fire_department': Icons.local_fire_department_rounded,
  'fitness_center': Icons.fitness_center_rounded,
  'pets': Icons.pets_rounded,
  'child_care': Icons.child_care_rounded,
  'church': Icons.church_rounded,
  'local_cafe': Icons.local_cafe_rounded,
  'checkroom': Icons.checkroom_rounded,
  'build': Icons.build_rounded,
  'agriculture': Icons.agriculture_rounded,
  'sell': Icons.sell_rounded,
  'account_balance': Icons.account_balance_rounded,
  'volunteer_activism': Icons.volunteer_activism_rounded,
};

/// Icons offered when a user creates or edits a category.
const categoryIconKeys = [
  'home', 'shopping_cart', 'cleaning_services', 'directions_bus',
  'directions_car', 'bolt', 'water_drop', 'wifi', 'local_fire_department',
  'phone_android', 'medical_services', 'school', 'family_restroom',
  'child_care', 'restaurant', 'local_cafe', 'movie', 'shopping_bag',
  'checkroom', 'spa', 'fitness_center', 'pets', 'card_giftcard',
  'volunteer_activism', 'church', 'flight', 'build', 'work', 'storefront',
  'handyman', 'agriculture', 'sell', 'account_balance', 'trending_up',
  'redeem', 'savings', 'more_horiz',
];

IconData iconFor(String? key) => _icons[key] ?? Icons.more_horiz_rounded;
